export const categoryMap: Record<string, string> = {
  "Information Technology": "it-jobs",
  "Accounting & Finance": "accounting-finance-jobs",
  "Construction, Repair and Maintenance": "trade-construction-jobs",
  "Retail and Customer Service": "retail-customer-service-jobs",
  Healthcare: "healthcare-nursing-jobs",
  Manufacturing: "manufacturing-jobs",
  "Media Communications": "creative-design-jobs",
  "Financial Services": "accounting-finance-jobs",
  Telecommunications: "it-jobs",

  // Additional from moreCategories
  "Hotels & Travel Accommodation": "hospitality-catering-jobs",
  "Government & Public Administration": "admin-jobs",
  "Human Resources & Staffing": "hr-recruitment-jobs",
  "Aerospace & Defense": "engineering-jobs",
  Agriculture: "agriculture-jobs",
  "Arts, Entertainment & Recreation": "creative-design-jobs",
  Education: "teaching-jobs",
  "Energy, Mining & Utilities": "energy-oil-gas-jobs",
  "Real Estate": "property-jobs",
  Insurance: "accounting-finance-jobs",
  "Personal Consumer Services": "customer-services-jobs",
  "Restaurants & Food Service": "hospitality-catering-jobs",
  "Transportation & Logistics": "logistics-warehouse-jobs",
  Legal: "legal-jobs",
  "Pharmaceutical & Biotechnology": "healthcare-nursing-jobs",
  "Nonprofit & NGO": "charity-voluntary-jobs",
  "Management & Consulting": "consultancy-jobs",
};
