export const categoryMap: Record<string, string> = {
  "Information Technology": "it-jobs",
  "Accounting & Finance": "accounting-finance-jobs",
  "Trade and Construction": "trade-construction-jobs",
  "Retail a": "retail-jobs",
  "Healthcare and Nursing": "healthcare-nursing-jobs",
  Manufacturing: "manufacturing-jobs",
  "Creative & Design": "creative-design-jobs",
  "Financial Services": "accounting-finance-jobs",
  "PR, Advertising & Marketing": "pr-advertising-marketing-jobs",

  // Additional from moreCategories
  "Hospitality & Catering": "hospitality-catering-jobs",
  "Government & Public Administration": "admin-jobs",
  "Human Resources & Recuritment": "hr-recruitment-jobs",
  Engineering: "engineering-jobs",
  Agriculture: "agriculture-jobs",
  "Social Work": "social-work-jobs",
  "Arts, Entertainment & Recreation": "creative-design-jobs",
  Education: "teaching-jobs",
  "Energy, Mining & Utilities": "energy-oil-gas-jobs",
  "Real Estate": "property-jobs",
  Insurance: "accounting-finance-jobs",
  "Customer Service": "customer-services-jobs",
  Travel: "travel-jobs",
  "Transportation & Logistics": "logistics-warehouse-jobs",
  Legal: "legal-jobs",
  Sales: "sales-jobs",
  Graduate: "graduate-jobs",
  "Scientific & QA": "scientific-qa-jobs",
  "Nonprofit & NGO": "charity-voluntary-jobs",
  "Management & Consulting": "consultancy-jobs",
  "Other/General": "other-general-jobs",
};
