export const jobIndustries = [
  "Financial Services",
  "Healthcare",
  "Hotels & Travel Accommodation",
  "Manufacturing",
  "Government & Public Administration",
  "Information Technology",
  "Construction, Repair and Maintenance",
  "Media Communications",
  "Retail and Customer Service",
  "Telecommunications",
  "Human Resources & Staffing",
  "Aerospace & Defense",
  "Agriculture",
  "Arts, Entertainment & Recreation",
  "Education",
  "Energy, Mining & Utilities",
  "Real Estate",
  "Insurance",
  "Personal Consumer Services",
  "Restaurants & Food Service",
  "Transportation & Logistics",
  "Legal",
  "Pharmaceutical & Biotechnology",
  "Nonprofit & NGO",
  "Management & Consulting",
];
